### ISSUE TITLE
SD小人无法加载

### ISSUE THREAD

**Issue by Ruriko-Yuu** [Pelom777/AzurLaneTools#2]
SD小人页：
`Uncaught Error: Animation not found: stand
    at AnimationState2.setAnimation (Bone.ts:553:38)
    at index.vue:57:7
    at Signal2.dispatch (Signal.ts:138:22)
    at Loader2._onComplete (Loader.ts:548:25)
    at Loader.ts:591:26
    at next (AsyncQueue.ts:271:21)
    at Loader2.use (BoundingBoxAttachment.ts:41:28)
    at Loader.ts:568:20
    at AsyncQueue.ts:281:21`
resources.char.spineData.animations 数组是空的

**Comment by Pelom777** [comment]
哪个角色

**Comment by Pelom777** [comment]
还是说你自己build的？我改过pixi-spine的库[https://pelom.cn/archives/106/](https://pelom.cn/archives/106/)

**Comment by Ruriko-Yuu** [comment]
能用，好活！

**Comment by Ruriko-Yuu** [comment]
能用好活！修改后的包可以npm发布下，希望我是最后一个被坑的麻瓜😋
