### ISSUE TITLE
拉菲 II 小人无法显示

### ISSUE THREAD

**Issue by ZerolAcqua** [Pelom777/AzurLaneTools#7]
使用 Edge 和 Chrome 均出现此问题，查看莫加多尔和阿尔萨斯一切正常，推测拉菲 II 的相关资源存在问题。
报错信息如下：
```
Uncaught TypeError: Cannot read properties of undefined (reading 'baseTexture')
    at index.97c1d6a9.js:700:28375
    at n.dispatch (index.97c1d6a9.js:606:865)
    at index.97c1d6a9.js:606:20377
    at h (index.97c1d6a9.js:606:16649)
    at n.use (index.97c1d6a9.js:700:26976)
    at index.97c1d6a9.js:606:20333
    at index.97c1d6a9.js:606:16685
```

**Comment by Pelom777** [comment]
已修复
